spotify:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: spotify
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default
