repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        stages: [commit]
        args: [--line-length=100]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        stages: [commit]
        # args: [--config=setup.cfg]
        args: [--config=setup.cfg, "--ignore=F401"]
